[package]
name = "rustdemoapi"
version = "0.2.0"
authors = ["Timo Schütz <mail@tschuetz.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "2.0"
actix-rt = "1.0"
sys-info = "0.7"